version: '3.8'
services:
  backend:
    container_name: backend
    build: backend/
    ports:
      - "3000:3000"
    depends_on:
      - db
  frontend:
    container_name: frontend
    build: frontend/
    ports:
      - "80:80"
    environment:
      - PORT=80
      - CHOKIDAR_USEPOLLING=true
#    volumes:
#      - './frontend:/app'
    stdin_open: true
    depends_on:
      - backend
  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
volumes:
  mongodb_data_container:
